application: foodie-pedia
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/images
  static_dir: static/images
  # mime_type: image/png


- url: /stylesheets
  static_dir: stylesheets
  mime_type: text/css

- url: /js
  static_dir: js


- url: /.*
  script: main.application

libraries:
- name: jinja2
  version: latest

- name: webapp2
  version: latest
